#!/usr/bin/env python3
"""Build claims-pass3.csv from ROADMAP + MASTER_PLAN + CHANGELOG (recent)."""
import csv
RUN_ID = "20260715-170152-3a51cba"
OUT = f"e2e-audit/{RUN_ID}/claims/claims-pass3.csv"

HEADER = [
    "claim_id", "texto_resumido", "fonte_arquivo", "fonte_linha",
    "categoria", "superficie_publica", "comportamento_esperado",
    "peso", "criticidade", "observacao",
]

CLAIMS = [
    # ---- ROADMAP (Sprint status) ----
    ("CLM-A0-198", "Sprint 32 (Audit3040_v2) fechado com 76% cobertura; 7 fases 60->74->79->98->126->177->221->266 regras portadas",
     "ROADMAP.md", "20", "validacao", "API",
     "contagem 266 regras 3040 portadas", "5", "core",
     "setimo numero distinto para 3040 (alem de 25, 60, 126, 275, 320, 275/361)"),
    ("CLM-A0-199", "Sprint 33 (Audit3050) fechado com 170 regras TXB_V11; 6 fases 28->56->80->97->153->170; carry-over permanente 5 stubs DB",
     "ROADMAP.md", "21", "validacao", "API",
     "3050 totalmente coberto exceto 5 stubs", "3", "supporting", ""),
    ("CLM-A0-200", "Sprint 43 (CrossDoc_v2) fechado com 8 regras XD01-XD08 entregues",
     "ROADMAP.md", "45", "validacao", "API",
     "registry retorna >= 8 regras cross-doc", "5", "core",
     "contradiz ADR-0006 que lista 12 regras XD01-XD12"),
    ("CLM-A0-201", "Sprint 49 (DRSAC_v1) entregou 35 regras D01-D35",
     "ROADMAP.md", "62", "validacao", "API",
     "/v1/rules/2030 retorna >= 35", "3", "supporting",
     "contradiz tabela README linha 57 que diz 0 regras DRSAC"),
    ("CLM-A0-202", "Sprint 50 (DRSAC_v2) entregou 8 regras cross-doc DRSAC<->SCR",
     "ROADMAP.md", "63", "validacao", "API",
     "engine cross-doc roda regras DRSAC", "3", "supporting", ""),
    ("CLM-A0-203", "Sprint 51 (Audit4111) entregou parser generico 4111",
     "ROADMAP.md", "64", "geracao", "API",
     "/v1/generate/4111 roda e gera XML", "3", "supporting", ""),
    ("CLM-A0-204", "Sprint 56 (SOC2_Type1) fechou readiness + evidence collector",
     "ROADMAP.md", "69", "compliance", "runtime",
     "evidencia SOC 2 Type I disponivel", "3", "supporting", ""),
    ("CLM-A0-205", "Sprint 65 (SOC2_Type2) fechou continuous evidence collection",
     "ROADMAP.md", "89", "compliance", "runtime",
     "evidencia SOC 2 Type II disponivel", "3", "supporting", ""),
    ("CLM-A0-206", "Sprint 63 (MultiRegion) entregou replicacao BR-SP1/SP2",
     "ROADMAP.md", "87", "deployment", "deploy",
     "Postgres replica assincrona configurada", "3", "supporting", ""),
    ("CLM-A0-207", "Sprint 57 (NormaGeneratorFoundation) - decisao tomada 2026-07-08, implementacao backlog",
     "ROADMAP.md", "81", "geracao", "API",
     "status declarado vs entrega real", "5", "core",
     "data de decisao 2026-07-08 bate com data dos ADRs 0007/0008 'nao iniciado'"),
    ("CLM-A0-208", "Sprint 34 (FrontendNext) marcado pendente (Next.js 15 App Router + RSC)",
     "ROADMAP.md", "25", "ui", "build",
     "Console migrado para Next.js 15", "3", "supporting", ""),
    ("CLM-A0-209", "Sprint 36 (Observability) marcado pendente (OTel + Sentry + Better Stack)",
     "ROADMAP.md", "27", "observabilidade", "runtime",
     "traces + errors + logs estruturados", "3", "supporting", ""),
    ("CLM-A0-210", "Sprint 37 (Pilot) marcado pendente (onboarding SCD-piloto 30-90 dias)",
     "ROADMAP.md", "28", "negocio", "deploy",
     "SCD piloto pagante", "3", "supporting", ""),
    ("CLM-A0-211", "Milestones: M1 piloto pagante 2026-09-30; M2 10 clientes 2026-12-31; M3 ESG vendido 2027-03-31; M4 Series A ready 2027-06-30",
     "ROADMAP.md", "127", "negocio", "negocio",
     "datas batem com a realidade operacional", "1", "marketing", ""),
    ("CLM-A0-212", "Backlog tooling: Sprint 34-T AuditForge POC (cmd/synth-gen + internal/synth) - Challenger LLM + Weak Solver + Judge LLM",
     "ROADMAP.md", "102", "geracao", "runtime",
     "Autodata-style data sintética para CADOCs", "1", "marketing", ""),
    # ---- MASTER_PLAN §0 Principios ----
    ("CLM-A0-213", "Manifesto: latencia de geracao <= 5 min; cobertura executavel >= 90%; audit <= 60s",
     "MASTER_PLAN.md", "16", "deployment", "runtime",
     "SLOs batem com §2.5", "3", "supporting", ""),
    ("CLM-A0-214", "P1 Schema-first generator-agnostic: motor usa Schema Registry como source-of-truth",
     "MASTER_PLAN.md", "27", "geracao", "build",
     "Generator consome schema registry, nao hardcoded", "5", "core", ""),
    ("CLM-A0-215", "P2 Multi-tenant desde nascimento: Postgres RLS obrigatorio; nenhum WHERE if_id no codigo de aplicacao",
     "MASTER_PLAN.md", "28", "seguranca", "runtime",
     "codigo nao tem WHERE if_id; RLS no DB", "5", "core", ""),
    ("CLM-A0-216", "P3 Audit tudo sempre: cada mutacao emite 1 entrada na hash chain verificavel em O(n)",
     "MASTER_PLAN.md", "29", "seguranca", "runtime",
     "audit chain detecta qualquer adulteracao", "5", "core", ""),
    ("CLM-A0-217", "P4 Fail-fast fail-loud: erros de config causam panic no boot (nao 503 em runtime)",
     "MASTER_PLAN.md", "30", "deployment", "runtime",
     "API nao sobe com config invalida", "3", "supporting", ""),
    ("CLM-A0-218", "P5 Defense-in-depth em secrets: senha Sisbacen nunca em log/erro/flag CLI visivel em ps",
     "MASTER_PLAN.md", "31", "seguranca", "runtime",
     "scan de segredos em CI", "5", "core", ""),
    ("CLM-A0-219", "P9 Spec antes de implementar: toda sprint comeca com SPRINT_*_RESEARCH.md",
     "MASTER_PLAN.md", "35", "deployment", "CI",
     "sprint inicia com research", "1", "supporting", ""),
    ("CLM-A0-220", "P10 Operacao por contrato: SLOs publicados; violacao = post-mortem publico",
     "MASTER_PLAN.md", "36", "compliance", "runtime",
     "SLOs batem com §2.5; post-mortem publicado", "3", "supporting", ""),
    ("CLM-A0-221", "U2 '0 -> envio em 15 min': onboarding self-service, wizard guiado",
     "MASTER_PLAN.md", "44", "ui", "runtime",
     "tempo de onboarding <= 15 min", "3", "supporting", ""),
    ("CLM-A0-222", "U6 Real-time por padrao: SSE/WebSocket nativo; Radar alert aparece em < 3s",
     "MASTER_PLAN.md", "47", "ui", "runtime",
     "SSE conecta e entrega eventos", "3", "supporting", ""),
    # ---- MASTER_PLAN §1 Roadmap ----
    ("CLM-A0-223", "Sprint 32 (Audit3040_v2) listado com 80+ regras restantes; coverage 16% -> 60%",
     "MASTER_PLAN.md", "82", "validacao", "API",
     "contradiz ROADMAP que diz fechado em 76%", "3", "supporting",
     "duas metricas divergentes: 60% alvo vs 76% realizado"),
    ("CLM-A0-224", "Sprint 33 (Audit3050) com 170 regras TXB_V11; XSD ja tem no BACEN, parser XML + 170 regras",
     "MASTER_PLAN.md", "83", "validacao", "API",
     "implementado em 100%", "3", "supporting", ""),
    # ---- MASTER_PLAN §2.5 SLOs ----
    ("CLM-A0-225", "SLOs: API availability 99.9% (43 min downtime/mes); latency P95 validate < 500ms; submit < 2s; STA round-trip < 5s; SSE < 3s; Radar < 24h; Audit chain 100%",
     "MASTER_PLAN.md", "260", "deployment", "runtime",
     "metricas de producao batem com SLOs declarados", "5", "core", ""),
    # ---- MASTER_PLAN §5 Quality Gates ----
    ("CLM-A0-226", "Cobertura minima por pacote: audit/rules 85% (atual 62.8%); crossdoc/rules 70% (atual 28.3%); db 75% (atual 68.4%); auth 85% (atual 71.8%)",
     "MASTER_PLAN.md", "2007", "deployment", "build",
     "coberturas declaradas batem com go test -cover", "5", "core",
     "audit/rules 62.8% esta ABAIXO do minimo 85% - NAO CONFORME"),
    ("CLM-A0-227", "Latencia P95: validate < 500ms; sta/submit < 5s; schemas < 100ms; rules < 200ms; audit_log < 500ms; insights/kpis < 1s; SSE < 3s",
     "MASTER_PLAN.md", "2031", "deployment", "runtime",
     "endpoints medidos batem com targets", "3", "supporting", ""),
    ("CLM-A0-228", "Seguranca: TLS 1.3 only; HSTS+CSP+X-Frame-Options; zero secrets em logs/errors/responses; JWT RS256 com rotacao de chave; rate limit 100 req/min por IF; CSRF origin check; audit chain verificavel em O(n); govulncheck sem CVEs high/critical; gosec sem findings high; pen test anual",
     "MASTER_PLAN.md", "2045", "seguranca", "runtime",
     "todos os controles implementados e ativos", "5", "core", ""),
    ("CLM-A0-229", "Performance budgets: API binary < 50MB; API RSS < 500MB por instancia; cold start < 2s; DB pool 20 idle/100 max; SSE 10k por instancia; webhook delivery P95 < 30s; frontend bundle < 200KB por rota gzipped; LCP < 2.5s; FID < 100ms",
     "MASTER_PLAN.md", "2059", "deployment", "runtime",
     "metricas batem com os budgets declarados", "3", "supporting", ""),
    # ---- MASTER_PLAN §3.5 Epic E ----
    ("CLM-A0-230", "Postgres RLS migration 014_rls_enforce.sql habilita FORCE ROW LEVEL SECURITY em envios, audit_log, criticas_disabled, recommendations_ack, envios_stats, rule_prefs",
     "MASTER_PLAN.md", "599", "seguranca", "runtime",
     "todas as 6 tabelas com FORCE RLS", "5", "core",
     "README linha 246 confirma 6 tabelas tenant-scoped"),
    ("CLM-A0-231", "App-side wiring Go: withTenantContext(ifID, fn) com BeginTx + SET LOCAL app.current_if_id",
     "MASTER_PAN.md", "621", "seguranca", "runtime",
     "helper obrigatorio em toda query", "5", "core", ""),
    ("CLM-A0-232", "Tenant struct: ID, CNPJ, RazaoSocial, TipoIF (SCD/IP/Banco/Cooperativa/DTVM), Plano (lite/pro/scale/enterprise), StripeID, Status (active/suspended/deleted), SisbacenUser encrypted, SisbacenSecretRef AWS SM ARN, BACENHomolog bool",
     "MASTER_PLAN.md", "640", "seguranca", "runtime",
     "modelo de tenant cobre todos os campos", "5", "core", ""),
    ("CLM-A0-233", "Onboarding flow wizard 6 steps: CNPJ/razao; tipo IF+plano; Sisbacen creds testadas in-process; admin email+2FA; smoke BACEN real automatico; welcome dashboard",
     "MASTER_PLAN.md", "660", "ui", "runtime",
     "wizard implementa todos os 6 steps", "3", "supporting", ""),
    ("CLM-A0-234", "Planos: Lite R$1500, Pro R$4500, Scale R$12000, Enterprise custom; billing mensal por IF ativa",
     "MASTER_PLAN.md", "670", "negocio", "billing",
     "billing Stripe operacional", "3", "supporting", ""),
    # ---- MASTER_PLAN §3.9 Epic I Generator ----
    ("CLM-A0-235", "5 camadas: INGEST (Manual UI / PDF-XLSX-DOCX / API / DB / MCP) -> CANONICAL -> MAPPER (COSIF+LLM) -> EMITTER (structs Go -> XML) -> VALIDATOR (L1-L4+crossdoc+historico) -> SUBMITTER (STA/DRRSystem)",
     "MASTER_PLAN.md", "919", "geracao", "build",
     "5 camadas implementadas", "5", "core", ""),
    ("CLM-A0-236", "CADOCGenerator interface: CadocCode, Generate, RequiredFields",
     "MASTER_PLAN.md", "934", "geracao", "build",
     "interface implementada", "5", "core", ""),
    ("CLM-A0-237", "GeneratedDoc: XML + ZIP + SHA256 + Errors + FieldMap (Field, Value, Source, RuleRef, Confidence)",
     "MASTER_PLAN.md", "943", "geracao", "build",
     "explainability campo-a-campo presente", "5", "core", ""),
    ("CLM-A0-238", "SourceAdapter interface: Name, Fetch, ValidateConfig, HealthCheck",
     "MASTER_PLAN.md", "960", "ingestao", "build",
     "5 implementacoes (Manual, File, API, DB, MCP)", "5", "core", ""),
    ("CLM-A0-239", "CanonicalDocument: Metadata + Accounting + Credit + Deposits + Limits + Liquidity + ESG + Market + Custom",
     "MASTER_PLAN.md", "978", "geracao", "build",
     "schema canonico cobre todos os dominios", "5", "core", ""),
    ("CLM-A0-240", "COSIFMapper: lookup direto + fuzzy match + LLM fallback com confidence score; persiste mapeamento -> gold-set",
     "MASTER_PLAN.md", "1000", "geracao", "build",
     "mapper funciona com fallbacks", "3", "supporting", ""),
    ("CLM-A0-241", "Cobertura por CADOC no Epic I: todos os 10 marcados como entregues (Gen3040, Gen3050, Gen4111, GenDLO, GenDLI, GenDDR, GenDRL, GenDLP, GenDRM, GenDRSAC)",
     "MASTER_PLAN.md", "1018", "geracao", "API",
     "10 generators funcionais", "5", "core",
     "contradiz CHANGELOG v3.36.0 que diz apenas 3040 implementado; v3.36.3 amplia para 10 no registry"),
    # ---- MASTER_PLAN §9 Riscos ----
    ("CLM-A0-242", "Risco regulatorio: BACEN exige certificacao especifica - mitigacao SOC 2 Type II + ISO 27001 roadmap",
     "MASTER_PLAN.md", "2732", "compliance", "compliance",
     "certificacoes obtidas e vigentes", "1", "marketing", ""),
    ("CLM-A0-243", "Risco: LLM gera valor inventado no Canonical - mitigacao LLM nunca escreve XML direto; canonical model tipado + validacao L1-L4 downstream",
     "MASTER_PLAN.md", "2720", "geracao", "build",
     "LLM emite JSON tipado; XML sempre de Go", "5", "core", ""),
    # ---- CHANGELOG v3.36.4 ----
    ("CLM-A0-244", "v3.36.4 fix H1 (HIGH): handlers usavam genRegistry package-level global em init() ao inves de Server.GeneratorRegistry; wiring em cmd/api/main.go era cosmetico",
     "CHANGELOG.md", "13", "geracao", "build",
     "fix corrigido e testes verdes", "5", "core",
     "confirma que wiring de registry era stub ate v3.36.3"),
    ("CLM-A0-245", "v3.36.4 fix H2 (HIGH): data race em staRangeUpload response; Session.ReceivedBytes/Ranges/Status lidos FORA do sessionsMu.Lock",
     "CHANGELOG.md", "17", "seguranca", "runtime",
     "race detector clean", "5", "core",
     "data race em codigo de producao - bloqueador"),
    ("CLM-A0-246", "v3.36.4 fix M1 (MEDIUM): batch handler chamava ValidateFull E engine.Validate separadamente executando engine 2x",
     "CHANGELOG.md", "21", "validacao", "runtime",
     "50% menos CPU em batch", "3", "supporting", ""),
    ("CLM-A0-247", "v3.36.4 fix M5 (MEDIUM): err.Error() leak em staRangeInit expondo URL/hostname/status",
     "CHANGELOG.md", "26", "seguranca", "runtime",
     "log detalhado server-side; userError generico", "5", "core",
     "vazamento de informacao - bloqueador"),
    # ---- CHANGELOG v3.36.3 ----
    ("CLM-A0-248", "v3.36.3 fix 1: generator.NewRegistry() retornava registry VAZIO; Registry.Get('3040') retornava nil em producao",
     "CHANGELOG.md", "44", "geracao", "API",
     "fix chama generator.RegisterDefaults em cmd/api/main.go", "5", "core",
     "registro de generators NAO existia antes do fix - bloqueador grave"),
    ("CLM-A0-249", "v3.36.3 fix 2: Manual + File adapters FALTAVAM; antes 3/5 adapters (DB, API, MCP); Manual e File eram stubs",
     "CHANGELOG.md", "48", "ingestao", "API",
     "ManualAdapter e FileAdapter adicionados", "5", "core",
     "contradiz ON_PREMISE_LLM_SPEC que diz '5 conectores incluindo MCP'; verdade e 3 ate v3.36.2"),
    ("CLM-A0-250", "v3.36.3 fix 3: validation.ValidateBatch definido mas SEM CALLER; cross-doc era chamado direto sem L1-L3",
     "CHANGELOG.md", "52", "validacao", "API",
     "validation.ValidateFull wirado em /v1/generate/batch", "5", "core",
     "ValidateBatch existia como dead code"),
    ("CLM-A0-251", "v3.36.3 fix 4: synth-gen so suportava 3 CADOCs (3040/3050/4111); expandido para 10",
     "CHANGELOG.md", "56", "geracao", "runtime",
     "enum CadocType expandido", "3", "supporting", ""),
    ("CLM-A0-252", "v3.36.3 fix 5: wizard sem backward navigation; Step.Prev() + Store.Revindicate() + handler direction=prev",
     "CHANGELOG.md", "60", "ui", "runtime",
     "wizard permite voltar e editar", "3", "supporting", ""),
    ("CLM-A0-253", "v3.36.3: +30 testes (sta_range_handlers, xd_rules, wizard/session, synth/cadoc, registry, manual_file)",
     "CHANGELOG.md", "65", "deployment", "build",
     "suites passam", "3", "supporting", ""),
    ("CLM-A0-254", "v3.36.3 fixes durante testes: mergeRanges panic; s.DB nil-check; TestBatchGenerate_MultipleCADOCs esperava 200 mas agora 422 (correto)",
     "CHANGELOG.md", "74", "geracao", "build",
     "bugs corrigidos", "3", "supporting", ""),
    ("CLM-A0-255", "v3.36.3 suite completa verde (60+ packages); ~1500 LOC adicionados; go build ./... clean; 6 commits granulares",
     "CHANGELOG.md", "80", "deployment", "build",
     "metricas reproduzidas", "3", "supporting", ""),
    # ---- CHANGELOG v3.36.0 ----
    ("CLM-A0-256", "v3.36.0: novos pacotes internal/canonical, internal/generator, internal/generator/gen3040, internal/ingest",
     "CHANGELOG.md", "99", "geracao", "build",
     "pacotes existem", "5", "core", ""),
    ("CLM-A0-257", "v3.36.0: 5 conectores listados mas 4 retornam 'nao implementado' - apenas Manual funcional",
     "CHANGELOG.md", "107", "ingestao", "API",
     "Manual funcional; outros stubs", "5", "core",
     "bate com gaps conhecidos README linha 323"),
    ("CLM-A0-258", "v3.36.0: API endpoints novos /v1/generate/{cadoc}, /fields, /sources, /adapters",
     "CHANGELOG.md", "108", "geracao", "API",
     "4 endpoints existem", "5", "core", ""),
    ("CLM-A0-259", "v3.36.0: CLI go run ./cmd/generator-server (list/adapters/generate)",
     "CHANGELOG.md", "117", "geracao", "runtime",
     "binario compila e roda", "3", "supporting", ""),
    ("CLM-A0-260", "v3.36.0: Gen3040 agrupa operacoes por (modalidade, UF, tpCli, classOp, faixa) e soma em Venc[v110..v165]",
     "CHANGELOG.md", "133", "geracao", "runtime",
     "generator 3040 produz XML correto", "5", "core", ""),
    ("CLM-A0-261", "v3.36.0 cobertura: apenas 3040 implementado; 9 CADOCs restantes planejados Sprint 58",
     "CHANGELOG.md", "141", "geracao", "API",
     "registry.Get retorna 1 ou 10 generators", "5", "core",
     "bate com gaps conhecidos README linha 322"),
    # ---- CHANGELOG v3.36.2 ----
    ("CLM-A0-262", "v3.36.2: code review fixes aplicados",
     "CHANGELOG.md", "319", "deployment", "build",
     "patch de qualidade", "1", "supporting", ""),
    # ---- CHANGELOG v3.34.51 ----
    ("CLM-A0-263", "v3.34.51 (2026-07-07): AuditForge POC com cmd/synth-gen + internal/synth (Challenger LLM + Weak Solver + Judge LLM)",
     "CHANGELOG.md", "730", "geracao", "runtime",
     "POC funciona", "1", "marketing", ""),
    # ---- CHANGELOG v3.34.47 ----
    ("CLM-A0-264", "v3.34.47: Sprint 65 SOC 2 Type II - continuous evidence collection",
     "CHANGELOG.md", "837", "compliance", "runtime",
     "evidence collector implementado", "3", "supporting", ""),
    # ---- CHANGELOG v3.34.45 ----
    ("CLM-A0-265", "v3.34.45: Sprint 63 MultiRegion - BR-SP1/SP2 replication",
     "CHANGELOG.md", "878", "deployment", "deploy",
     "replicacao Postgres configurada", "3", "supporting", ""),
    # ---- CHANGELOG v3.34.44 ----
    ("CLM-A0-266", "v3.34.44: Sprint 62 Marketplace - catalogo de regras customizadas (publish/install/rate)",
     "CHANGELOG.md", "891", "ui", "runtime",
     "marketplace funcional", "3", "supporting", ""),
    # ---- CHANGELOG v3.35.6 ----
    ("CLM-A0-267", "v3.35.6 (2026-07-08): Pivo estrategico - decisao de arquitetura Sprint 57 (implementacao backlog)",
     "CHANGELOG.md", "158", "geracao", "API",
     "decisao documentada, implementacao a confirmar", "5", "core", ""),
    # ---- CHANGELOG v3.35.5 ----
    ("CLM-A0-268", "v3.35.5 (2026-07-08): Login direto via cookie dev (sem JWT bridge) - simplificacao",
     "CHANGELOG.md", "396", "seguranca", "runtime",
     "cookie auth dev funcional", "3", "supporting",
     "contradiz P5/P10 com seguranca forte; simplificacao em dev"),
    # ---- CHANGELOG v3.35.3 ----
    ("CLM-A0-269", "v3.35.3 (2026-07-08): cmd/seed-demo - seeder de dados realistas",
     "CHANGELOG.md", "438", "deployment", "build",
     "seed-demo roda e popula DB", "3", "supporting", ""),
    # ---- CHANGELOG v3.35.2 ----
    ("CLM-A0-270", "v3.35.2 (2026-07-08): separa landing de console",
     "CHANGELOG.md", "468", "ui", "build",
     "landing e console em rotas separadas", "1", "supporting", ""),
    # ---- CHANGELOG v3.34.52 ----
    ("CLM-A0-271", "v3.34.52 (2026-07-07): Pilot endpoints auth bypass - security fix",
     "CHANGELOG.md", "696", "seguranca", "runtime",
     "pilot endpoints requerem auth", "5", "core",
     "vulnerabilidade corrigida em v3.34.52 - confirmar nao recorrente"),
    # ---- Inconsistencias e contradições ----
    ("CLM-A0-272", "README tabela linha 66 diz '10 generators entregues'; CHANGELOG v3.36.0 diz apenas 3040 implementado",
     "README.md + CHANGELOG.md", "66/141", "geracao", "API",
     "verificar quantos estao implementados de verdade", "5", "core",
     "v3.36.3 amplia registry para 10; implementacao completa ainda so do 3040"),
    ("CLM-A0-273", "ROADMAP linha 45 diz '8 regras cross-doc XD01-XD08'; ADR-0006 linha 86 lista 12 regras; README linha 236 diz 1 entregue",
     "ROADMAP.md + ADR-0006 + README.md", "45/86/236", "validacao", "API",
     "verificar quantas estao implementadas", "5", "core",
     "3 fontes com 3 numeros distintos: 1, 8, 12"),
    ("CLM-A0-274", "MASTER_PAN §3.9 lista todos os 10 generators com status ✅; CHANGELOG v3.36.0 lista apenas 3040 ✅",
     "MASTER_PLAN.md + CHANGELOG.md", "1018/141", "geracao", "API",
     "MASTER_PLAN otimista; CHANGELOG conservador", "5", "core",
     "a versao real e: 10 registrados (v3.36.3) mas so 3040 com geracao implementada"),
    ("CLM-A0-275", "MASTER_PLAN §2.2 (topologia) menciona 'PostgreSQL SKIP LOCKED (nao RabbitMQ)' para queue/worker; nao encontrei ainda confirmacao em codigo",
     "MASTER_PLAN.md", "169", "deployment", "runtime",
     "verificar uso de SKIP LOCKED em worker", "3", "supporting", ""),
    ("CLM-A0-276", "MASTER_PLAN §5.1 cobertura minima audit/rules = 85% (atual 62.8%) - declaradamente abaixo do minimo",
     "MASTER_PLAN.md", "2007", "deployment", "build",
     "cobertura de audit/rules ABaixo do minimo declarado", "5", "core",
     "CI gate deveria falhar; verificar se gate esta aplicado"),
    ("CLM-A0-277", "MASTER_PLAN §3.8 SOC 2 readiness: PagerDuty on-call rotation, post-mortem template, vendor management AWS/Stripe/Sentry/Keycloak",
     "MASTER_PLAN.md", "891", "compliance", "runtime",
     "processos de SRE funcionando", "3", "supporting",
     "verificar se ha PagerDuty configurado em ambiente"),
    ("CLM-A0-278", "MASTER_PLAN §3.5 E.4 acceptance criteria: auditoria externa (consultoria) valida isolamento",
     "MASTER_PLAN.md", "688", "seguranca", "compliance",
     "relatorio de auditoria externa existe", "1", "marketing",
     "claim de auditoria externa - nao testavel sem o relatorio"),
    ("CLM-A0-279", "MASTER_PLAN §3.6 F.3 DRSAC validado contra BCValidador byte-a-byte (acceptance criteria)",
     "MASTER_PLAN.md", "725", "geracao", "compliance",
     "DRSAC byte-a-byte igual ao BCValidador", "5", "core",
     "comparacao com oraculo externo - precisamos do BCValidador"),
]

# Sanity
for c in CLAIMS:
    assert len(c) == 10, f"{c[0]} has {len(c)} fields"

with open(OUT, "w", newline="") as f:
    w = csv.writer(f, quoting=csv.QUOTE_MINIMAL)
    w.writerow(HEADER)
    for c in CLAIMS:
        w.writerow(c)

print(f"Wrote {len(CLAIMS)} claims to {OUT}")